### ISSUE TITLE
RadioGroup should have props like KendoComboBox

### ISSUE THREAD

**Issue by newyankeecodeshop** [wingspan/wingspan-forms#81]
A radio group is logically an alternative to a dropdown or combo for selecting a single value from a list of choices. Therefore, it would be much more convenient to have the RadioGroup props align with KendoComboBox/KendoDropDownList. So radios would be populated by an array-based DataSource, and there would be a standard value/onChange pair.

**Comment by dustingetz** [comment]
Note that there is a more general use of radios e.g. the case on the Work Area where there are combos inside of radios

**Comment by newyankeecodeshop** [comment]
Right, and for that, there's no need for RadioGroup. You can just put two <Radio> components in a <fieldset> or <div>. I think the value in <RadioGroup> is making it really simple to generate a list of choices. Right now, it's little more than a wrapper around a <fieldset> that doesn't even transfer basic props like className to the fieldset element.

**Comment by dustingetz** [comment]
> Right now, it's little more than a wrapper ...

I don't think this is true, RadioGroup also [adapts the "value/onChange" interface to the "checked" interface](https://github.com/wingspan/wingspan-forms/blob/master/js/controls/RadioGroup.js#L20-23) on the dom, which is something that the Composite use case needs as well (I think, this is tough to wrap my head around without seeing the work area code again)

**Comment by newyankeecodeshop** [comment]
Alas, it only adopts the "value" part of value/onChange. You still have to put onChange handlers on every child Radio. 
I agree it's necessary sometimes to use direct Radio children. I think both mechanisms, dataSource or child Radios, can be supported.
