### ISSUE TITLE
NPM package includes multiple copies of Kendo-UI

### ISSUE THREAD

**Issue by markerikson** [wingspan/wingspan-forms#89]
I'm trying to install Wingspan-Forms from NPM using the JSPM package manager.  It kept rejecting my install attempts, saying that the "Response is too large".  Did some digging, and JSPM appears to have a hardcoded 50MB size limit for package downloads.  Why, I don't know, but it's there.

So unfortunately, it looks like the current release of wingspan-forms is 58MB.  I pulled down a copy using "npm cache add wingspan-forms" and opened it up to see why it's so big.  It looks like the release process includes a complete copy of Kendo-UI for every single example app in the repo.  I see 10 copies each of kendo.web.js (2MB each), kendo.web.min.js.map (1MB each), kendo.web.min.js (750K each), etc, plus all the globalization files.

This seems very wasteful. Would it be possible to either strip all those copies of Kendo out of the package, or restructure the build process so that there's only one copy bundled into the release, or something similar?

**Comment by newyankeecodeshop** [comment]
Yes, the duplication in all the example apps is unfortunate. Also, given that Kendo seems to do releases outside of npm, I think it will make more sense to remove it from the package.json. It needs to be included outside the npm dependency process.

**Comment by newyankeecodeshop** [comment]
I've removed it now. It's "BYOK" - Bring Your Own Kendo.
