### ISSUE TITLE
Cleanup warnings for React 0.14

### ISSUE THREAD

**Issue by newyankeecodeshop** [wingspan/wingspan-forms#91]
Mostly need to convert `this.getDOMNode()` to `ReactDOM.findDOMNode(this)`.
There's also a hack in TabStrip.js that modified props.

**Comment by thomasmodeneis** [comment]
Hi,

How do you get this to work with React 14?
I'm having errors for this version:
```
npm WARN saveError peer invalid: jquery@~1.9.1, required by wingspan-forms@0.9.3
npm WARN saveError peer invalid: kendo-ui-core@~1.0.0, required by wingspan-forms@0.9.3
npm WARN saveError peer invalid: react@~0.13.0, required by wingspan-forms@0.9.3
```

**Comment by newyankeecodeshop** [comment]
I have some upgrades for React 0.14 as well as other features almost ready to commit. I should have them pushed up this week,

**Comment by thomasmodeneis** [comment]
Hi @newyankeecodeshop 

Is this by any chance works for server-side rendering ?

I've been trying to do this with the actual code but there is so many things to fix that I could not see the end.

Thanks

**Comment by newyankeecodeshop** [comment]
I have never tried server-side rendering with this library, but I'm not surprised there are issues. I'm sure the fact that the code is written in AMD (requireJS) style doesn't help, although I'm planning on changing the build to webpack as part of a new wave of changes.
What other kinds of problems do you see?

**Comment by thomasmodeneis** [comment]
The first main issue is that this code is not allowed:
```
/** @jsx React.DOM */
```

After I removed all this components and ran into the issue of the requireJS and I had to convert all classes one by one to react model and correct the imports one by one and changing from:

```
define([
    './AutoControl',
    './FormField',
], function (AutoControl, FormField ...
```

to react portion of it:

```import {AutoControl} from "./AutoControl"```

But the errors where just everywhere, they started to annoy me when I got to have to change internals of the Kendo because they also don't work. :(

**Comment by newyankeecodeshop** [comment]
Hopefully we should only be referencing kendo widgets in the code that deals with mount/unmount. I guess that's not the case.
